name: dp-solver-env
channels:
  - pytorch
  - akode
  - conda-forge
  - defaults
  - dglteam
dependencies:
  - absl-py=0.6.1
  - astor=0.7.1
  - bzip2=1.0.6
  - c-ares=1.15.0
  - cryptography-vectors=2.3.1
  - gast=0.2.0
  - h5py=2.8.0
  - hdf5=1.10.3
  - libgpuarray=0.7.6
  - libprotobuf=3.6.1
  - mako=1.0.7
  - markdown=2.6.11
  - markupsafe=1.1.0
  - matplotlib
  - matplotlib-base
  - progressbar2=3.37.1
  - protobuf=3.6.1
  - pygpu=0.7.6
  - pyyaml=3.13
  - termcolor=1.1.0
  - werkzeug=0.14.1
  - yaml=0.1.7
  - asn1crypto=0.24.0
  - blas=1.0
  - ca-certificates=2019.1.23
  - cairo=1.14.12
  - certifi=2018.11.29
  - cffi=1.11.5
  - chardet=3.0.4
  - cryptography=2.4.2
  - cycler=0.10.0
  - decorator=4.3.0
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gettext=0.19.8.1
  - glib=2.56.2
  - graphite2=1.3.13
  - graphviz=2.40.1
  - grpcio=1.16.1
  - harfbuzz=1.8.8
  - icu=58.2
  - idna=2.7
  - intel-openmp=2019.0
  - jpeg=9b
  - kiwisolver=1.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libiconv=1.15
  - libpng=1.6.35
  - libtiff=4.0.10
  - libxml2=2.9.9
  - ncurses=6.1
  - networkx=2.2
  - ninja=1.8.2
  - numpy=1.15.4
  - numpy-base=1.15.4
  - openssl=1.1.1a
  - pango=1.42.4
  - pcre=8.42
  - pip=10.0.1
  - pixman=0.36.0
  - pycparser=2.19
  - pydot=1.3.0
  - pyopenssl=18.0.0
  - pyparsing=2.2.2
  - pysocks=1.6.8
  - python=3.6.7
  - python-dateutil=2.7.3
  - pytz=2018.5
  - readline=7.0
  - requests=2.20.0
  - scikit-learn=0.20.0
  - scipy=1.2.0
  - setuptools=40.4.3
  - six=1.11.0
  - tensorboard=1.12.2
  - tk=8.6.9
  - tornado=5.1.1
  - tqdm=4.31.1
  - urllib3=1.23
  - wheel=0.32.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pytorch=1.2.0
  - torchvision
  - dgl=0.4.3
